### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [ivan3123708/chat-app#3]
Hello...

I Came across your great project and as someone who loves to contribute to open source projects, I wanted to help contribute to your amazing project by using my Skills in LOGO DESIGN to create a logo/icon for your project...

I am currently working on some cool ideas... Once i'm done, I will post the idea concepts here so you can give me your feedback to make changes or tweak to suit your needs.

Regards.

**Comment by ivan3123708** [comment]
Hello @chimzycash. I'm sorry for late answer...
Logo would be great, I'll be glad if you contribute (if you're still interested :))

**Comment by chimzycash** [comment]
Awesome... I appreciate the response, 
I will get the concept ready and send it here for your feedback.

**Comment by chimzycash** [comment]
Hello @ivan3123708 
Here is my idea concept design... I would love to read your feedback and also, you can suggest the logo color(s) of your choice.

![LOGO DESIGN_CHAT APP_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/56699022-ca5dbf80-66eb-11e9-909d-e701e90ccb87.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/56699232-96cf6500-66ec-11e9-8022-02da53a2e7c4.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/56699023-ca5dbf80-66eb-11e9-9a8e-e5dab66351ed.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/56699024-caf65600-66eb-11e9-8684-ce457de79d1a.jpg)
![LOGO DESIGN_CHAT APP_idea concept_NEW](https://user-images.githubusercontent.com/37814297/56699026-cb8eec80-66eb-11e9-8476-b2fc865517e0.jpg)

**Comment by ivan3123708** [comment]
Great work, I like it.

Would be nice if you could make the logo from example below with background colors used in all themes:
```
{
  violet: #746db4
  black: #263238
  grey: #dedef7
  pink: #ff95c7
  green: #92db25
}
```
...and white text. For the gray background you can use pink (#ff95c7) text. It can be 250px width to fit into sidebar.

<img src="https://user-images.githubusercontent.com/37814297/56699023-ca5dbf80-66eb-11e9-9a8e-e5dab66351ed.jpg"/>

And also, logo from the same picture with violet text and transparent background would look very nice on login page.

If you have any suggestions, please let me know. Thanks for you work again :+1:

**Comment by chimzycash** [comment]
Awesome...Here are the changes

![LOGO DESIGN_CHAT APP_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/56788400-4f81cb00-67f7-11e9-81f5-c8f9e4bfe59a.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_1a](https://user-images.githubusercontent.com/37814297/56788402-501a6180-67f7-11e9-9f16-58abad872a39.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_1b](https://user-images.githubusercontent.com/37814297/56788403-50b2f800-67f7-11e9-84c6-b73047d14163.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_1c](https://user-images.githubusercontent.com/37814297/56788407-514b8e80-67f7-11e9-8aa9-ea16e14991be.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_1d](https://user-images.githubusercontent.com/37814297/56788448-6f18f380-67f7-11e9-810a-68fa1438285a.jpg)
![LOGO DESIGN_CHAT APP_BACKGROUND_1e](https://user-images.githubusercontent.com/37814297/56788409-527cbb80-67f7-11e9-918a-795ef4daa74f.jpg)

**Comment by ivan3123708** [comment]
Great, I updated the app with added logos.

**Comment by chimzycash** [comment]
@ivan3123708  Would prepare all the transparent files + Vector files and update them here for your use

**Comment by chimzycash** [comment]
Hi @ivan3123708 
Here is the google drive link containing the files + the vector files

https://drive.google.com/drive/folders/1qM9U79nMr0hE773GrEb4NT-ZWUQKcBbE?usp=sharing

**Comment by ivan3123708** [comment]
Thanks @chimzycash, as soon as I have time, I will merge your PR.
